//! Linux desktop integration.
//!
//! On X11 and Windows the window icon set through `ViewportBuilder::with_icon`
//! is enough. On Wayland it is not: winit lists `set_window_icon` as unsupported
//! there, because Wayland had no protocol for a client to hand the compositor
//! raw icon pixels. The shell instead matches a window's `app_id` against an
//! installed `.desktop` file and takes the icon from the icon theme — so on
//! Wayland the taskbar icon is a packaging problem, not a rendering one.
//!
//! The file name must be `giverny.desktop` to match the `app_id` set in `main`.

use std::fs;
use std::path::{Path, PathBuf};

/// Icon sizes, paired with the bytes generated by `tools/pixelmark/make_icons.py`.
const ICONS: &[(u32, &[u8])] = &[
    (16, include_bytes!("../../../assets/icon/giverny-16.png")),
    (32, include_bytes!("../../../assets/icon/giverny-32.png")),
    (48, include_bytes!("../../../assets/icon/giverny-48.png")),
    (64, include_bytes!("../../../assets/icon/giverny-64.png")),
    (128, include_bytes!("../../../assets/icon/giverny-128.png")),
    (256, include_bytes!("../../../assets/icon/giverny-256.png")),
    (512, include_bytes!("../../../assets/icon/giverny-512.png")),
];

fn data_home() -> Option<PathBuf> {
    match std::env::var_os("XDG_DATA_HOME") {
        Some(dir) if !dir.is_empty() => Some(PathBuf::from(dir)),
        _ => std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".local/share")),
    }
}

fn desktop_path(data: &Path) -> PathBuf {
    data.join("applications/giverny.desktop")
}

fn icon_path(data: &Path, size: u32) -> PathBuf {
    data.join(format!("icons/hicolor/{size}x{size}/apps/giverny.png"))
}

/// Best-effort cache refresh. Neither tool is guaranteed present, and GNOME
/// picks the files up on its own eventually, so failure is not an error.
fn refresh(data: &Path) {
    let _ = std::process::Command::new("update-desktop-database")
        .arg(data.join("applications"))
        .status();
    let _ = std::process::Command::new("gtk-update-icon-cache")
        .args(["-f", "-t"])
        .arg(data.join("icons/hicolor"))
        .status();
}

pub fn install() {
    if !cfg!(target_os = "linux") {
        println!("install-desktop is Linux-only; the embedded window icon covers this platform.");
        return;
    }
    let Some(data) = data_home() else {
        eprintln!("error: neither XDG_DATA_HOME nor HOME is set — cannot find a place to install");
        std::process::exit(1);
    };

    let exec = match std::env::current_exe() {
        Ok(path) => path,
        Err(err) => {
            eprintln!("error: cannot resolve this executable's path: {err}");
            std::process::exit(1);
        }
    };

    let entry = format!(
        "[Desktop Entry]\n\
         Type=Application\n\
         Name=Giverny\n\
         GenericName=Terminal\n\
         Comment=A native GPU terminal built around Claude Code\n\
         Exec={exec}\n\
         Icon=giverny\n\
         Terminal=false\n\
         Categories=System;TerminalEmulator;\n\
         Keywords=terminal;shell;claude;prompt;\n\
         StartupNotify=true\n\
         StartupWMClass=giverny\n",
        exec = exec.display()
    );

    let mut written = Vec::new();
    for (size, bytes) in ICONS {
        let path = icon_path(&data, *size);
        if let Some(parent) = path.parent()
            && let Err(err) = fs::create_dir_all(parent)
        {
            eprintln!("error: cannot create {}: {err}", parent.display());
            std::process::exit(1);
        }
        if let Err(err) = fs::write(&path, bytes) {
            eprintln!("error: cannot write {}: {err}", path.display());
            std::process::exit(1);
        }
        written.push(path);
    }

    let entry_path = desktop_path(&data);
    if let Some(parent) = entry_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    if let Err(err) = fs::write(&entry_path, entry) {
        eprintln!("error: cannot write {}: {err}", entry_path.display());
        std::process::exit(1);
    }

    refresh(&data);

    println!("installed {}", entry_path.display());
    println!(
        "installed {} icons under {}",
        written.len(),
        data.join("icons/hicolor").display()
    );
    println!("\nExec points at {}", exec.display());
    println!("Rebuild somewhere else and re-run this to update it.");
    println!("Restart Giverny for the shell to pick up the icon.");
}

pub fn remove() {
    let Some(data) = data_home() else {
        eprintln!("error: neither XDG_DATA_HOME nor HOME is set");
        std::process::exit(1);
    };
    let mut gone = 0;
    for (size, _) in ICONS {
        if fs::remove_file(icon_path(&data, *size)).is_ok() {
            gone += 1;
        }
    }
    let entry = desktop_path(&data);
    let had_entry = fs::remove_file(&entry).is_ok();
    refresh(&data);

    if had_entry || gone > 0 {
        println!(
            "removed {} icon(s){}",
            gone,
            if had_entry {
                " and the desktop entry"
            } else {
                ""
            }
        );
    } else {
        println!("nothing to remove — no Giverny desktop entry or icons were installed");
    }
}

/// Whether the desktop entry is in place, for `doctor`.
pub fn status() -> Option<(PathBuf, bool)> {
    let data = data_home()?;
    let entry = desktop_path(&data);
    let installed = entry.is_file();
    Some((entry, installed))
}
