//! The Giverny mark, embedded as pixels.
//!
//! `mark.rs` is generated by `tools/pixelmark/make_icons.py` from
//! `tools/pixelmark/marks/giverny.pix`. Edit the `.pix` and re-run the script;
//! never edit the generated file.

mod mark;

pub use mark::{GIVERNY_H, GIVERNY_RGBA, GIVERNY_W};

/// The mark at `scale`×, nearest-neighbour, ready for [`egui::ViewportBuilder::with_icon`].
///
/// Upscaling here rather than baking a 256×256 array into the source keeps the
/// generated file at a kilobyte and leaves the size choice with the caller.
/// Nearest-neighbour is the whole point — a pixel mark must never be smoothed,
/// and every window-system size we care about is an integer multiple of 16.
pub fn icon_data(scale: u32) -> egui::IconData {
    debug_assert!(scale > 0, "icon scale must be at least 1");
    let (width, height) = (GIVERNY_W * scale, GIVERNY_H * scale);
    let mut rgba = Vec::with_capacity((width * height * 4) as usize);
    for y in 0..height {
        for x in 0..width {
            let src = (((y / scale) * GIVERNY_W + (x / scale)) * 4) as usize;
            rgba.extend_from_slice(&GIVERNY_RGBA[src..src + 4]);
        }
    }
    egui::IconData {
        rgba,
        width,
        height,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scaling_preserves_pixels() {
        let icon = icon_data(4);
        assert_eq!(icon.width, 64);
        assert_eq!(icon.height, 64);
        assert_eq!(icon.rgba.len(), 64 * 64 * 4);
        // every pixel in a 4x4 source cell must be identical
        let at = |x: usize, y: usize| &icon.rgba[(y * 64 + x) * 4..(y * 64 + x) * 4 + 4];
        assert_eq!(at(0, 0), at(3, 3));
        assert_eq!(at(32, 32), at(35, 35));
    }

    #[test]
    fn centre_is_the_gold_core() {
        let icon = icon_data(1);
        let px = &icon.rgba[(7 * 16 + 7) * 4..(7 * 16 + 7) * 4 + 4];
        assert_eq!(px, [0xf0, 0xd1, 0x78, 0xff]);
    }
}
